name: Update items in project
on:
  issues:
    types: [closed]

jobs:
  add_to_project:
    name: Project Update
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/project-update@v1
        with:
          # The number of the project. Get this from the URL.
          project-number: 1
          # The item Id of the issue or pull request.
          item-id: 11
          # The GITHUB_TOKEN secret
          github-token: ${{ secrets.token }}
          # The user that owns the project.
          user: 'BryanGoesWu'
          # CSV fields to modify.
          fields: No Status
          # CSV fields values.
          fields-value: Closed
      

