name: Update work item state when PR is merged, opened, closed or when branch is created

on:
   issues:
    branches: [master]
    types: [opened, edited]
    

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:       
    - uses: MarcinGadomski94/pr-update-work-item-state@master
      env: 
        gh_token : '${{ secrets.GITHUB_TOKEN }}'   
        ado_token: '${{ secrets.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 }}'
        ado_project: '${{ secrets.Automation_Testing }}'
        closedstate: 'Done'
        ghrepo_owner: 'BryanGoesWu'
        ghrepo: 'WorkflowTesting'
        pull_number: ${{github.event.number}} 
        branch_name: ${{ github.ref }}

