name: "Add Issue/PR to Project"
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    name: Add to Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: austenstone/project-add@main
        with:
          user: ${{ github.repository_owner }}
          project-number: 1
          github-token: "${{ secrets.token }}"
        id: project-add
      - uses: austenstone/project-update@main
        with:
          user: ${{ github.repository_owner }}
          project-number: 5
          github-token: "${{ secrets.token }}"
          item-id: ${{ steps.project-add.outputs.id }}
          field-names: product,priority
          field-values: back-end,high

